[project]
name = "topologic"
version = "0.4"
description = "Yet Another Topic Modeling Browser, tied to PhiloLogic"
authors = [
    { name = "The ARTFL Project", email = "clovisgladstone@gmail.com" },
]
requires-python = ">=3.11"
dependencies = [
    "scikit-learn",
    "pandas",
    "scipy",
    "numpy",
    "tqdm",
    "joblib",
    "matplotlib",
    "fastapi==0.110.3",
    "gunicorn",
    "uvicorn",
    "uvloop",
    "httptools",
    "annoy",
    "psycopg2",
    "multiprocess",
    "text_preprocessing",
    "philologic>=4.7.4.4",
    "torch",
    "spacy-transformers",
    "cupy-cuda12x",
]

[tool.uv.sources]
text_preprocessing = { git = "https://github.com/ARTFL-Project/text-preprocessing", tag = "v1.1.2" }
torch = { index = "pytorch-cu124" }

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["topologic*"]
